sudo: required
language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker build -t cornelc/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true cornelc/react-test npm test
after_success:
  - docker build -t cornelc/multi-client ./client
  - docker build -t cornelc/multi-nginx ./nginx
  - docker build -t cornelc/multi-server ./server
  - docker build -t cornelc/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cornelc/multi-client
  - docker push cornelc/multi-nginx
  - docker push cornelc/multi-server
  - docker push cornelc/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY